#################################################################
###################### Hexo Configuration #######################
#################################################################

title: NexT

keywords: "Hexo, NexT"

language: en

index_generator:
  per_page: 4
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

timezone: UTC

url: https://theme-next.org
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

skip_render:
- 'robots.txt'

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 5
pagination_dir: page

theme: next

deploy:
  type: git
  repo: https://github.com/theme-next/theme-next.org.git
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

server:
  port: 4000

kramed:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.json
  field: all

symbols_count_time:
  symbols: false
  time: false
  total_symbols: false
  total_time: false


#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:

  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  reminder: true

  minify: true

  custom_file_path:
    variable: source/_data/variables.styl
    footer: source/_data/footer.swig
    sidebar: source/_data/sidebar.swig


  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2014
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: NexT
    powered:
      enable: false
      version: false
    theme:
      enable: false
      version: false

  creative_commons:
    license: by-nc-sa
    sidebar: true


  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini


  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    News: / || bullhorn

    Docs:
      default: /docs/ || book

      Getting Started:
        default: /getting-started/ || flag
        Installation: /installation.html || download
        Deployment: /deployment.html || upload
        Data Files: /data-files.html || wrench
        Update from 5.x: /update-from-v5.html || retweet

      Theme Settings:
        default: /theme-settings/ || star
        Footer: /footer.html || sun-o
        Sidebar: /sidebar.html || bars
        Posts: /posts.html || pencil-square-o
        Custom Pages: /custom-pages.html || file-o
        SEO: /seo.html || external-link-square
        Front Matter: /front-matter.html || header

      Third Party Services:
        default: /third-party-services/ || plug
        Math Equations: /math-equations.html || superscript
        Comment Systems: /comments.html || comments-o
        Statistics and Analytics: /statistics-and-analytics.html || bar-chart
        Post Widgets: /post-widgets.html || share-square
        Search Services: /search-services.html || search-plus
        Chat Services: /chat-services.html || comment
        External Libraries: /external-libraries.html || puzzle-piece

      Tag Plugins:
        default: /tag-plugins/ || rocket
        Note: /note.html || comment
        Tabs: /tabs.html || columns
        PDF: /pdf.html || file-pdf-o
        Mermaid: /mermaid.html || tasks
        Label: /label.html || font
        Video: /video.html || video-camera
        Button: /button.html || square
        Caniuse: /caniuse.html || signal
        Group Pictures: /group-pictures.html || file-image-o

      Advanced Settings: /advanced-settings.html || cogs
      FAQ's: /faqs.html || life-ring
      Troubleshooting: /troubleshooting.html || bug
    archives: /archives/ || archive
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  menu_settings:
    icons: true
    badges: true


  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  sidebar:
    position: left
    display: post
    padding: 18
    offset: 12
    onmobile: true

  avatar:
    url: /images/apple-touch-icon-next.png
    rounded: true

  social:
    GitHub: https://github.com/theme-next || github
    E-Mail: mailto:support@theme-next.org || envelope
    RSS: /atom.xml || rss

    Gitter: https://gitter.im/theme-next || github-alt
    Riot: https://riot.im/app/#/room/#NexT:matrix.org || bullhorn

    Telegram [Chat]: https://t.me/joinchat/GUNHXA-vZkgSMuimL1VmMw || telegram
    Telegram [News]: https://t.me/theme_next || paper-plane

  social_icons:
    enable: true
    icons_only: true
    transition: true

  toc:
    enable: true
    number: true
    wrap: true


  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 4
    wpm: 275

  post_edit:
    enable: true
    url: https://github.com/theme-next/theme-next.org/edit/source/source/


  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true

  back2top:
    enable: true
    sidebar: false
    scrollpercent: true

  github_banner:
    enable: true
    permalink: https://github.com/theme-next/hexo-theme-next
    title: Fork NexT on GitHub


  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  seo: true

  index_with_subtitle: true

  exturl: true

  yandex_site_verification: 3ac9ae36ddebb425


  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #

  math:
    per_page: true
    mathjax:
      enable: true

  mediumzoom: true

  lazyload: true


  # ============================================================= #
  # =================== Comments and Widgets ==================== #
  # ============================================================= #

  disqus:
    enable: true
    shortname: theme-next
    count: true
    lazyload: true


  # ============================================================= #
  # ================= Statistics and Analytics ================== #
  # ============================================================= #


  # ============================================================= #
  # ====================== Search Services ====================== #
  # ============================================================= #

  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    preload: true


  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    light_bg_offset: -3

  tabs:
    transition:
      tabs: true
      labels: true


  # ============================================================= #
  # ==================== External Libraries ===================== #
  # ============================================================= #

  motion:
    enable: false
