#################################################################
###################### Hexo Configuration #######################
#################################################################

title: NexT

keywords: "Hexo, NexT"

language: en

index_generator:
  per_page: 4
  order_by: -date

archive_generator:
  per_page: 8
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 5

tag_generator:
  per_page: 5
  enable_index_page: false

timezone: UTC

url: https://theme-next.org
root: /
permalink: :title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives/
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

skip_render:
- 'robots.txt'

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 5
pagination_dir: page

theme: next

deploy:
  type: git
  repo: https://github.com/theme-next/theme-next.org.git
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"

server:
  port: 4000

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  # For disable links in code blocks.
  autolink: false

kramed:
  # For preserve original quotes in code blocks.
  smartypants: false

search:
  path: search.xml
  field: all

symbols_count_time:
  symbols: false
  time: false
  total_symbols: false
  total_time: false


#################################################################
###################### NexT Configuration #######################
#################################################################

theme_config:

  # ============================================================= #
  # ============= Theme Core Configuration Settings ============= #
  # ============================================================= #

  cache:
    enable: true

  custom_file_path:
    styles: source/_data/styles.styl


  # ============================================================= #
  # ======================= SEO Settings ======================== #
  # ============================================================= #

  seo: true
  index_with_subtitle: true
  exturl: true


  # ============================================================= #
  # ====================== Scheme Settings ====================== #
  # ============================================================= #

  #scheme: Muse
  #scheme: Mist
  #scheme: Pisces
  scheme: Gemini


  # ============================================================= #
  # ================= Site Information Settings ================= #
  # ============================================================= #

  footer:
    since: 2014
    icon:
      name: heart
      animated: true
      color: "#808080"
    copyright: NexT
    # -------------------------------------------------------------
    powered:
      enable: true
      version: true
    theme:
      enable: true
      version: true
    custom_text: Theme source code <span class="exturl theme-link" data-url="aHR0cHM6Ly9naXRodWIuY29tL3RoZW1lLW5leHQvaGV4by10aGVtZS1uZXh0">here</span><br>Website source code <span class="exturl theme-link" data-url="aHR0cHM6Ly9naXRodWIuY29tL3RoZW1lLW5leHQvdGhlbWUtbmV4dC5vcmc=">here</span>

  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: false


  # ============================================================= #
  # ======================= Menu Settings ======================= #
  # ============================================================= #

  menu:
    News: / || bullhorn

    Docs:
      default: /docs/ || book

      Getting Started:
        default: /getting-started/ || flag
        Installation: /installation/ || download
        Deployment: /deployment/ || upload
        Data Files: /data-files/ || wrench
        Update from 5.x: /update-from-v5/ || retweet

      Theme Settings:
        default: /theme-settings/ || star
        Footer: /footer/ || sun-o
        Custom Pages: /custom-pages/ || file-o
        Posts: /posts/ || pencil-square-o
        Sidebar: /sidebar/ || bars
        ExtURL: /exturl/ || external-link-square

      Third Party Services:
        default: /third-party-services/ || plug
        Comments and Widgets: /comments-and-widgets/ || comments-o
        Statistics and Analytics: /statistics-and-analytics/ || bar-chart
        Content Sharing Services: /content-sharing-services/ || share-square
        Search Services: /search-services/ || search-plus
        External Libraries: /external-libraries/ || puzzle-piece
        Math Equations: /math-equations/ || superscript

      Tag Plugins:
        default: /tag-plugins/ || rocket
        Full Image: /full-image/ || picture-o
        Note: /note/ || comment
        Button: /button/ || square
        Label: /label/ || font
        Tabs: /tabs/ || columns
        Mermaid: /mermaid/ || tasks
        Video: /video/ || video-camera
        Group Pictures: /group-pictures/ || file-image-o
        PDF: /pdf/ || file-pdf-o

      Advanced Settings: /advanced-settings/ || cogs
      FAQ's: /faqs/ || life-ring
      Troubleshooting: /troubleshooting/ || bug
    archives: /archives/ || archive
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  menu_settings:
    icons: true
    badges: true


  # ============================================================= #
  # ===================== Sidebar Settings ====================== #
  # ============================================================= #

  avatar:
    url: /images/apple-touch-icon-next.png
    rounded: true
    opacity: 1
    rotated: false

  social:
    GitHub: https://github.com/theme-next || github
    E-Mail: mailto:support@theme-next.org || envelope

    Gitter: https://gitter.im/theme-next || github-alt
    Riot: https://riot.im/app/#/room/#NexT:matrix.org || bullhorn

    Telegram [Chat]: https://t.me/joinchat/GUNHXA-vZkgSMuimL1VmMw || telegram
    Telegram [News]: https://t.me/theme_next || telegram

  social_icons:
    enable: true
    icons_only: true
    transition: true

  github_banner: https://github.com/theme-next/hexo-theme-next || Fork NexT on GitHub

  toc:
    enable: true
    number: true
    wrap: true

  sidebar:
    b2t: true
    scrollpercent: true
    onmobile: true


  # ============================================================= #
  # ======================= Post Settings ======================= #
  # ============================================================= #

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: true
    awl: 4
    wpm: 275

  post_edit:
    enable: true
    url: https://github.com/theme-next/theme-next.org/edit/source/source/


  # ============================================================= #
  # ==================== Misc Theme Settings ==================== #
  # ============================================================= #

  mobile_layout_economy: true


  # ============================================================= #
  # =============== Third Party Services Settings =============== #
  # ============================================================= #


  # ============================================================= #
  # ------------------- Comments and Widgets -------------------- #
  # ============================================================= #

  disqus:
    enable: true
    shortname: theme-next
    count: true
    lazyload: true


  # ============================================================= #
  # ----------------- Statistics and Analytics ------------------ #
  # ============================================================= #

  yandex_site_verification: 3ac9ae36ddebb425


  # ============================================================= #
  # ---------------------- Search Services ---------------------- #
  # ============================================================= #

  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1


  # ============================================================= #
  # -------------------- External Libraries --------------------- #
  # ============================================================= #

  motion:
    enable: false
    async: true
    transition:
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideUpIn

  lazyload: true


  # ============================================================= #
  # ---------------------- Math Equations ----------------------- #
  # ============================================================= #

  math:
    enable: true
    per_page: true
    engine: mathjax
    mathjax:
      cdn: //cdn.jsdelivr.net/npm/mathjax@2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML


  # ============================================================= #
  # ======================== Tag Plugins ======================== #
  # ============================================================= #

  note:
    style: simple
    icons: true
    border_radius: 0
    light_bg_offset: -3

  tabs:
    enable: true
    transition:
      tabs: true
      labels: true
    border_radius: 0
