[Settings]
ID = "Theme-Next"

# ================ #
#       Test       #
# ================ #
#[[redirects]]
#  from = "https://theme-next.org/schemes/test/*"
#  to = "https://test.theme-next.org/:splat"
#  status = 301
#  force = false

[[redirects]]
  from = "https://test.theme-next.org/*"
  to = "https://theme-next.org/schemes/test/:splat"
  status = 200
  force = true


# ================ #
#       Muse       #
# ================ #
[[redirects]]
  from = "https://theme-next.org/schemes/muse/*"
  to = "https://muse.theme-next.org/:splat"
  status = 301
  force = false

[[redirects]]
  from = "https://muse.theme-next.org/*"
  to = "https://theme-next.org/schemes/muse/:splat"
  status = 200
  force = true


# ================ #
#       Mist       #
# ================ #
[[redirects]]
  from = "https://theme-next.org/schemes/mist/*"
  to = "https://mist.theme-next.org/:splat"
  status = 301
  force = false

[[redirects]]
  from = "https://mist.theme-next.org/*"
  to = "https://theme-next.org/schemes/mist/:splat"
  status = 200
  force = true


# ================ #
#      Pisces      #
# ================ #
[[redirects]]
  from = "https://theme-next.org/schemes/pisces/*"
  to = "https://pisces.theme-next.org/:splat"
  status = 301
  force = false

[[redirects]]
  from = "https://pisces.theme-next.org/*"
  to = "https://theme-next.org/schemes/pisces/:splat"
  status = 200
  force = true

# ================ #
#      Gemini      #
# ================ #
[[redirects]]
  from = "https://theme-next.org/schemes/gemini/*"
  to = "https://gemini.theme-next.org/:splat"
  status = 301
  force = false

[[redirects]]
  from = "https://gemini.theme-next.org/*"
  to = "https://theme-next.org/schemes/gemini/:splat"
  status = 200
  force = true


# ================ #
# Default (Gemini) #
# ================ #
[[redirects]]
  from = "https://theme-next.netlify.com/*"
  to = "https://theme-next.org/:splat"
  status = 301
  force = true